### ISSUE TITLE
Module prevents saving settings

### ISSUE THREAD

**Issue by 117Dios** [SaltyPretzel/pf2e-quick-creature-builder#3]
Hi,using find the culprit I found that this module makes me unable to save any settings in my world. When I press "Save" on the bottom of the settings window, nothing happens and if I close then reopen it, settings haven't changed.

**Comment by SaltyPretzel** [comment]
Hi,
I will look into this.  Could you post the version of foundry you are
seeing the problem on as well as any other modules you are using?

**Comment by 117Dios** [comment]
Hi, yes, version used was 12.329. Modules active were Quick Creature Builder and Find the Culprit. On the initial Find the Culprit check, the one where all modules were disabled except FtC itself, the problem wasn't present

**Comment by SaltyPretzel** [comment]
I have just released version 1.0.1 which should fix this issue.  It was caused by backend settings objects appearing in Foundry settings which I have now disabled
